P3 refactor inicial
elagarrigue/AyDS21-AK-Zeus3 pull request #2
Opened 2021-05-13 22:22 UTC by FGPetz

Terminamos el refactor de los archivos DataBase y OtherWindowInfo de la carpeta moredetails siguiendo los comentarios del último sprint.

2021-05-14 15:43 UTC, elagarrigue requested changes
En general revisar los nombres, que sean declarativos, y la responsabilidad única a nivel de función.

2021-05-14 15:43 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/DataBase.kt
> +class DataBase(context: Context): SQLiteOpenHelper(context,"dictionary.db", null, 1) {
- DataBase no es un nombre apropiado, demasiado general
- Definir constantes para el nombre y version de la db

2021-05-14 15:43 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/DataBase.kt
> +        this.put("source", 1)
Definir constantes para los nombres de las columnas

2021-05-14 15:43 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/DataBase.kt
> +            items[0]
Se puede simplificar
```suggestion
        return items.firstOrNull()
```

2021-05-14 15:43 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/DataBase.kt
> +                "create table artists (id INTEGER PRIMARY KEY AUTOINCREMENT, artist string, info string, source integer)")
definir una constante

2021-05-14 15:43 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/DataBase.kt
> +    private fun getCursorItems(cursor: Cursor) = ArrayList<String>().apply {
```suggestion
    private fun getInfoItems(cursor: Cursor) = ArrayList<String>().apply {
```

2021-05-14 15:43 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/DataBase.kt
> +        Log.i("DB", "DB created")
Remover log

2021-05-14 15:43 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +class OtherInfoWindow : AppCompatActivity() {
En android es buena práctica agregar el sufijo Activity
```suggestion
class OtherInfoActivity : AppCompatActivity() {
```

2021-05-14 15:43 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    private lateinit var textPane2: TextView
No es un nombre declarativo

2021-05-14 15:43 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        getArtistInfo()
No tiene el mismo nivel de abstracción. Comparar con home

2021-05-14 15:43 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    }
No tiene el mismo nivel de abstracción, hace muchas cosas y no es claro. Por ejemplo, pq se checkea por null el "text" (el cual no es un nombre claro), se inicia un thread, se llama a runOnUiThread, hay un string que debería ser una constante

2021-05-14 15:43 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        val snippet = getJsonElement("snippet")
definir la constante para el nombre de la propiedad del json

2021-05-14 15:43 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        text = snippet.asString.replace("\\n", "\n")
no pertenece al nivel de abstracción, mover a una sub función

2021-05-14 15:43 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    private fun saveToDatabase(text: String){
`text` no es declarativo, no revela intención

2021-05-14 15:43 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        }
hace dos cosas

2021-05-14 15:43 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    private fun getURL(): String {
nombre poco declarativo

2021-05-14 15:43 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        val urlString = "https://en.wikipedia.org/?curid=$pageid"
la construcción de este string es otro nivel de abstracción

2021-05-14 15:43 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        println("JSON " + callResponse.body())
eliminar logs innecesarios

2021-05-14 15:43 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    private fun getJsonElement(name: String): JsonElement{
El nombre no es declarativo

2021-05-14 15:43 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        return query["search"].asJsonArray[0].asJsonObject[name]
Hace muchas cosas

2021-05-14 15:43 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +            .baseUrl("https://en.wikipedia.org/w/")
constante

2021-05-14 15:43 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        val imageUrl = "https://upload.wikimedia.org/wikipedia/commons/8/8c/Wikipedia-logo-v2-es.png"
cosntante

2021-05-14 15:43 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +            .baseUrl("https://en.wikipedia.org/w/")
constante

2021-05-14 15:43 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        val imageUrl = "https://upload.wikimedia.org/wikipedia/commons/8/8c/Wikipedia-logo-v2-es.png"
constante

2021-05-14 15:43 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        textPane2.text = HtmlCompat.fromHtml(text, HtmlCompat.FROM_HTML_MODE_LEGACY)
Hace muchas cosas, nivel de abstracción

2021-05-14 15:43 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        textPane2.text = HtmlCompat.fromHtml(text, HtmlCompat.FROM_HTML_MODE_LEGACY)
Hace muchas cosas, nivel de abstracción

2021-05-14 15:43 UTC, elagarrigue requested changes
En general revisar los nombres, que sean declarativos, y la responsabilidad única a nivel de función.

2021-05-17 13:41 UTC, elagarrigue requested changes

2021-05-17 13:41 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/ArtistInfoStorage.kt
> +class ArtistInfoStorage(context: Context): SQLiteOpenHelper(context, DATABASE_NAME, null, DATABASE_VERSION) {
visibilidad

2021-05-17 13:41 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoActivity.kt
> +        dataBase = ArtistInfoStorage(this)
dividir en 3 pasos

2021-05-17 13:41 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoActivity.kt
> +        }.start()
nivel de abstr

2021-05-17 13:41 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoActivity.kt
> +            "[*]$infoArtistText"
constante

2021-05-17 13:41 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoActivity.kt
> +        }
hace 3 cosas

2021-05-17 13:41 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoActivity.kt
> +        return "https://en.wikipedia.org/?curid=$pageid"
constante

2021-05-17 13:41 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoActivity.kt
> +        return query["search"].asJsonArray[0].asJsonObject[name]
constantes nombres de las propiedades json

2021-05-17 13:41 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoActivity.kt
> +        val wikipediaAPI = retrofit.create(WikipediaAPI::class.java)
propiedades

2021-05-17 13:41 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoActivity.kt
> +        Picasso.get().load(IMAGE_WIKIPEDIA).into(findViewById<View>(R.id.imageView) as ImageView)
definir propiedad

2021-05-17 13:41 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoActivity.kt
> +        const val URL_WIKIPEDIA = "https://en.wikipedia.org/w/"
puede ser local

2021-05-18 19:20 UTC, elagarrigue requested changes

2021-05-18 19:20 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoActivity.kt
> +        wikipediaImage = Picasso.get().load(IMAGE_WIKIPEDIA)
Son distintos niveles de abstracción. Mover a diferentes funciones

2021-05-18 19:20 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoActivity.kt
> +        }.start()
Distinto nivel de abstracción, iniciar el thread y los dos pasos dentro

2021-05-18 19:20 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoActivity.kt
> +private const val LITERAL = "[*]"
no es un buen nombre. Mejor `STORED_PREFIX`

2021-05-18 19:20 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoActivity.kt
> +        return WIKIPEDIA_SHORT_URL+"$pageid"
la clase no esta bien indentada, formatear

2021-05-18 20:12 UTC, Fabri31295 commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoActivity.kt
> +        }.start()
Hola @elagarrigue, estamos con la duda de como refactorizar este caso. Deberiamos iniciar el thread en otra funcion y que dicha funcion tenga como unico paso showArtistInfo por ejemplo?

2021-05-18 20:35 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoActivity.kt
> +        }.start()
Claro, algo así

```
 private fun showArtistInfoAsync() {        
      Thread {            
         showArtistInfo()    
      }.start()
 }

 private fun showArtistInfo() {               
         urlString = updateWikipediaURL()           
         showArtistInfoActivity(getArtistInfo())        
 }
```

Otra cosa, urlString debería setearse en `updateWikipediaURL`, o la función llamarse `getWikipediaURL`

2021-05-19 12:41 UTC, elagarrigue requested changes
Está muy bien, últimos detalles

2021-05-19 12:41 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/ArtistInfoStorage.kt
> +        val dataBase = this.writableDatabase
esta variable no agrega valor, se puede hacer inline y eliminarla

2021-05-19 12:41 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/ArtistInfoStorage.kt
> +private const val CREATE_ARTISTS_TABLE :String =
no quedó bien formateada la clase,

2021-05-19 12:41 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoActivity.kt
> +    private fun initViewers() {
```suggestion
    private fun initViews() {
```

2021-05-19 12:41 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/OtherInfoActivity.kt
> +            .replace("(?i)" + term!!.toRegex(), "<b>" + term.toUpperCase(Locale.ROOT) + "</b>")
`!!` siempre es un smell, hay que tratar de evitarlo. En este caso, el parámetro term debería no ser nullable

2021-05-19 15:24 UTC, agus-tin9 commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/fulllogic/ArtistInfoStorage.kt
> +private const val CREATE_ARTISTS_TABLE :String =
Hola @elagarrigue, le hice Ctrl+Alt+L y eliminó identación de más, es esa la correción?
También cambiamos el string par que use las constantes
"create table $ARTISTS_TABLE (" +
            " $ID_COLUMN INTEGER PRIMARY KEY AUTOINCREMENT," +
            " $ARTIST_COLUMN string," +
            " $INFO_COLUMN string," +
            " $SOURCE_COLUMN integer)"

2021-05-21 16:07 UTC, FGPetz commented
Hola @elagarrigue, podemos empezar con lo que sigue o nos conviene esperar el merge?

2021-05-21 16:14 UTC, merged