P4 mvc
elagarrigue/AyDS21-AK-Zeus3 pull request #3
Opened 2021-05-29 23:24 UTC by Msent20

2021-05-31 13:51 UTC, elagarrigue requested changes
discutidos en el scrum

2021-06-02 14:08 UTC, Msent20 commented
> discutidos en el scrum

Hola Emma! Queriamos consultarte sobre ArticleDescriptionHelperImpl en el paquete View ya que no la estamos utilizando en ningún momento, donde se tendría que utilizar?

2021-06-02 14:34 UTC, elagarrigue commented
Debería ser el encargado de transformar la descripción a html

2021-06-07 12:01 UTC, elagarrigue requested changes
Falta la descripción del PR y el diagrama de clases

2021-06-08 11:51 UTC, elagarrigue requested changes
- Último cambio, dependencia no inyectada
- En el diagrama:
  - Nombres de los paquetes Home / MoreDetails, ponerlos en lower case como los paquetes reales
  - No cruzar relaciones entre paquetes, simplificar cambiando por relación paquete a paquete.  Por ej, el paquete controller depende del paquete view.

2021-06-08 11:51 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/view/MoreDetailsView.kt
> +    private val articleInfoHelper: ArticleDescriptionHelperImpl = ArticleDescriptionHelperImpl()
Inyectar esta dependencia!

2021-06-09 12:34 UTC, elagarrigue approved these changes
Ahí quedó 👍🏽

2021-06-09 12:34 UTC, merged