P5: Abstracción del servicio externo
elagarrigue/AyDS21-AK-Zeus3 pull request #4
Opened 2021-06-13 03:19 UTC by Msent20

- Generalizada el paquete More Details 
- Creación del submodulo y agregada la librería que contiene el paquete de lógica de comunicación con el servicio externo
- Agregado readme con explicación sobre cómo utilizar la librería
- Agregado en la UI un label que indica la fuente de donde proviene la información del artista

2021-06-18 20:04 UTC, Fabri31295 commented
@elagarrigue , terminamos de corregir lo que discutimos en el scrum, pero no sabemos si te llega la notificacion del request

2021-06-22 12:35 UTC, elagarrigue reviewed
Diagrama:
- Que el repositorio conozca el módulo externo para que quede más clara la estructura.

Submodule:
- Tener `Article` y `ArticleImpl` no suma nada, simplificar en una sola clase `Article`
- Readme:
   - Import module: poner el namespace completo
   - Instantiate an instance of the WikipediaService class -> Get an instance of the WikipediaService class.
   - `val wikipediaService: WikipediaModule.WikipediaService` -> `val wikipediaService: WikipediaModule.WikipediaService = WikipediaServiceModule.wikipediaService`

2021-06-22 12:35 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/view/MoreDetailsView.kt
> +            }
No cumple con open/close. Hay varias formas de solucionarlo:
- Agregar una propiedad al enumerado `name` https://kotlinlang.org/docs/enum-classes.html#implementing-interfaces-in-enum-classes
- Agregar una propiedad `sourceName` a la clase Card y setear ese string cuando se hace el mapeo del artículo a la Card.
Lo importante es que cada vez que se agregue un source, no haya que hacer cambios en varios lados

2021-06-22 12:35 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/view/MoreDetailsUiEvent.kt
> +    object OpenFullArticle : MoreDetailsUiEvent()
`OpenCardUrl`

2021-06-22 12:35 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/view/MoreDetailsUiEvent.kt
> +    object OpenFullArticle : MoreDetailsUiEvent()
`OpenCardUrl`

2021-06-22 12:35 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/controller/MoreDetailsController.kt
>      private fun showArtistInfoAsync() {
`showCardInfoAsync`

2021-06-22 12:35 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/model/repository/Source.kt
> +enum class Source{
Mover a `entities`

2021-06-22 12:35 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/model/repository/Source.kt
> +enum class Source{
Mover a `entities`

2021-06-22 12:35 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/model/repository/Source.kt
> +enum class Source{
Mover a `entities`

2021-06-22 12:35 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/model/repository/CardRepository.kt
> +    fun getCard(artistName: String): Card?
Debería retornar `Card` nunca null... Usar `EmptyCard` en vez de null en la implementación

2021-06-22 12:35 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/model/repository/local/CardTableConstants.kt
>  const val ARTISTS_TABLE = "artists"
card table

2021-06-22 12:35 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/model/repository/local/CardTableConstants.kt
>  const val ARTISTS_TABLE = "artists"
card table

2021-06-22 12:35 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/model/repository/local/CardTableConstants.kt
>  const val ARTISTS_TABLE = "artists"
card table

2021-06-22 12:35 UTC, elagarrigue reviewed
Diagrama:
- Que el repositorio conozca el módulo externo para que quede más clara la estructura.

Submodule:
- Tener `Article` y `ArticleImpl` no suma nada, simplificar en una sola clase `Article`
- Readme:
   - Import module: poner el namespace completo
   - Instantiate an instance of the WikipediaService class -> Get an instance of the WikipediaService class.
   - `val wikipediaService: WikipediaModule.WikipediaService` -> `val wikipediaService: WikipediaModule.WikipediaService = WikipediaServiceModule.wikipediaService`

2021-06-23 15:25 UTC, elagarrigue requested changes
Último cambio: `entities` les quedó dentro de repository, debería estar un nivel arriba

2021-06-23 16:27 UTC, elagarrigue approved these changes
🙌🏽

2021-06-23 16:27 UTC, merged