P6 broker
elagarrigue/AyDS21-AK-Zeus3 pull request #5
Opened 2021-07-01 19:31 UTC by Msent20

- Implementacion del broker
- Añadidos submodulos de otras comisiones
- Actualizacion de la ventana moreDetailsView para recibir la información de los 3 submodulos

obs.: aún no se actualizo el diagrama de clases correspondiente.

2021-07-02 13:21 UTC, elagarrigue requested changes
- Falta actualizar el diagrama.
- Tienen commiteados los archivos de libs/NYTimesData 🤔 . Reviertan ese cambio, deberían solamente ver el link al submódulo, como pasa con lastFm

2021-07-02 13:21 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/model/repository/broker/Broker.kt
> +class BrokerImpl(private val sourceToProxyMap: Map<Source,Proxy>) : Broker {
internal

2021-07-02 13:21 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/model/repository/broker/proxies/LastFMProxy.kt
> +    )
Comentario menor, el mapeo podría mapear la emptyCard
```suggestion
    override fun getCard(artistName: String): Card = service.getArtist(artistName).toCard()

    private fun InfoArtist?.toCard() =
        when {
            this == null -> EmptyCard()
            else -> Card(description, infoUrl, sourceLogoUrl, Source.LASTFM)
        }
```

2021-07-02 13:21 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/model/repository/local/CursorToCardMapper.kt
> +import android.util.Log
Remover import no utilizado

2021-07-02 13:21 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/view/MoreDetailsView.kt
> +        }
Se puede simplificar
```suggestion
        spinnerList.addAll(list.map { it.source.sourceName })
```

2021-07-02 13:21 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/view/MoreDetailsView.kt
> +    private var spinnerPosition: Int = 0
Debería estar en UiState

2021-07-02 13:21 UTC, elagarrigue commented on AK Zeus/app/src/main/java/ayds/zeus/songinfo/moredetails/view/MoreDetailsView.kt
> +        openExternalUrl(uiState.cardList[spinnerPosition].url)
`uiState.cardList[spinnerPosition]` debería ser un método de uiState, `getCurrentCard`

2021-07-05 18:16 UTC, elagarrigue requested changes
Diagrama:
- Falta la interfaz Proxy
- Broker depende de una lista de Proxy.  No hay objeto `List` y esta mal el asterisco, revisen la notación UML

2021-07-06 13:08 UTC, elagarrigue requested changes
Ejecución:
- Las fuentes aparecen duplicadas en el spinner
![Screenshot_1625587148](https://user-images.githubusercontent.com/5032371/124604005-e10e0e00-de40-11eb-8efe-c5ca2e3a20e9.png)
- Mientras se traen los datos en more details se puede apretar "view full article" y genera un crash. Lo mismo si no se encuentran resultados
- Un progress bar para indicar loading estaría bien
- Ejemplos de búsquedas:
  -  "rfrf" muestra un resultado, lastfm, sin descripción

2021-07-09 20:14 UTC, Msent20 commented
Hola @elagarrigue  ! Te queríamos hacer una consulta, en que casos le ocurrió las fuentes que aparecen duplicadas en el spinner porque nosotros testeandolo nunca nos pasó.
Perdón por las molestias.
Saludos.

2021-07-10 22:17 UTC, elagarrigue commented
Perdón, fue mi culpa. Hice un cambio local para ejemplificarles cómo simplificar la creación de la lista y me olvidé de revertirlo, así que localmente se me agregaron los elementos de la lista dos veces:
![Screenshot 2021-07-10 221729](https://user-images.githubusercontent.com/5032371/125177601-7bf54800-e1b3-11eb-86e1-8c37be9551b8.png)

Recuerden hacer el re request cuando estén listos.

2021-07-12 12:55 UTC, elagarrigue approved these changes
🙌🏽

2021-07-12 12:55 UTC, merged